Repository ZystemOS/pluto, pull requests merged in 2020-11, with the labels that each got.

#257 Add symlink support
  src/kernel/filesystem/initrd.zig
  src/kernel/filesystem/vfs.zig
Labels: hacktoberfest-accepted

#258 Check for memory leaks in all tests that allocate memory
  src/kernel/arch/x86/paging.zig
  src/kernel/bitmap.zig
  src/kernel/filesystem/initrd.zig
  src/kernel/panic.zig
  src/kernel/pmm.zig
  src/kernel/vmm.zig
  test/mock/kernel/mem_mock.zig
Labels: hacktoberfest-accepted

#263 mkFAT32 use a anytype stream
  build.zig
  mkfat32.zig
Labels: code quality, enhancement

#262 Rename the llog to logger to make is all consistent
  build.zig
  mkfat32.zig
  src/kernel/arch/x86/pci.zig
  src/kernel/kmain.zig
Labels: code quality
